### PR TITLE
Splitted up the render function of open-scd

### PR DESCRIPTION
**Pull request by pascalwilbrink**
To let extensions of open-scd be able to override the custom properties that are sent to the plugins, The pluginProperties function can be overridden by extensions of open-scd

### CODE REVIEW

**Comment by pascalwilbrink** [comment]
This could also be done by the spread function from `@open-wc`

Instead of
```ts
protected renderActiveEditor(): TemplateResult {
    return html`${this.editor
      ? staticHtml`<${unsafeStatic(this.editor)} docName="${
          this.docName || nothing
        }" .doc=${this.doc} locale="${this.locale}" .docs=${
          this.docs
        } .editCount=${this.editCount}></${unsafeStatic(this.editor)}>`
      : nothing}`;
}
```

this:

```ts
import { spread } from '@open-wc/lit-helpers';

...
protected renderActiveEditor(): TemplateResult {
    return html`${this.editor
      ? staticHtml`<${unsafeStatic(this.editor)} ${spread(this.activeEditorProperties())}></${unsafeStatic(this.editor)}>`
      : nothing}`;
}

  protected activeEditorProperties(): Map<string, string | number | boolean | object> {
    return new Map<string, string | number | boolean | object>(
      [
        [
          "docName", this.docName
        ],
        [
          "doc", this.doc
        ],
        [
          "locale", this.locale
        ],
        [
          "docs", this.docs
        ],
        [
          "editCount", this.editCount
        ]
      ]
    );
  }
```

**Comment by Sander3003** [comment]
@ca-d What is de status of this pull-request? Are we waiting for something/someone?

This pull-request is needed in order to create an OpenSCD-core extension for CoMPAS.

**Comment by pascalwilbrink** [comment]
Tests were already in place. No new tests were added (since there is no new functionality)

**Comment by Sander3003** [comment]
Waiting for @ca-d to review

**Comment by juancho0202** [comment]
LGTM

**Review by ca-d — DISMISSED** [review]
LGTM

**Review by ca-d — APPROVED** [review]
Thanks for fixing the tests, still LGTM.

**Pull request merged**
