### PR TITLE
fix(open-scd): hide menu plugin element container

### LINKED ISSUE #77: Menu plugins are not visible
When creating a menu plugin for open-scd-core, I was unable to bring the dialog to the foreground in either Firefox or Chrome.

Looking in the Chrome debugger tools, it was (eventually) noticed that the opacity was set to zero on the aside element and the plugin was inheriting this `opacity: 0`.

This is within the shadow-root of the open-scd element which has the structure:

```
<mwc-drawer id="menu"></mwc-drawer>
<mwc-dialog id="log"></mwc-dialog>
<aside>
    <oscd-{plugin-hash}>
    <oscd-{plugin-hash}>
    <oscd-{plugin-hash}>
    <oscd-{plugin-hash}>
</aside>

```

The constructed stylesheet for the `aside` element was:

```css
aside {
    position: absolute;
    top: 0px;
    left: 0px;
    width: 0px;
    height: 0px;
    overflow: hidden;
    opacity: 0;
    margin: 0px;
    padding: 0px;
}
```

I resolved this in my plugin with:

```js
  protected firstUpdated(): void {
    this.parentElement?.setAttribute('style', 'opacity: 1');
  }
```

Which restored visibility operation.

I can't presently see where/how this is set, so I can't do a PR to fix it. However, I will be happy to try with a hint. :wink:

### PR DESCRIPTION
**Pull request by ca-d**
Fixes #77 .

### CODE REVIEW

**Comment by JakobVogelsang** [comment]
I am not sure, but could we have a regression test for this?

**Comment by ca-d** [comment]
> I am not sure, but could we have a regression test for this?

Yes, we should totally add a screenshot test for this new behaviour. Something like showing a heading which is not displayed and then opening a dialog on click which is successfully displayed.

**Review by danyill — APPROVED** [review]
LGTM

**Comment by ca-d** [comment]
> LGTM

Thanks for leaving this comment, I didn't notice initially because it was not left in the form of a Review. I will assume that this is a succesful review and merge this pull request even though it is still blocked.

**Pull request merged**
